/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  important: '#root', // MUI와의 우선순위 충돌 방지
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary": "#f600a6",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#b43dc8",
        "inverse-on-surface": "#f2f0f0",
        "inverse-surface": "#303031",
        "secondary-container": "#0070eb",
        "surface-tint": "#bd0040",
        "surface-container-low": "#f5f3f3",
        "secondary-fixed-dim": "#adc6ff",
        "on-surface-variant": "#5d3f42",
        "on-tertiary-fixed": "#35003f",
        "on-surface": "#666666",
        "surface-variant": "#e4e2e2",
        "surface-container-high": "#e9e8e7",
        "on-secondary": "#ffffff",
        "on-tertiary-container": "#fff9fa",
        "on-primary-fixed": "#400010",
        "on-error": "#ffffff",
        "background": "#fbf9f8",
        "on-secondary-fixed": "#001a41",
        "error": "#ba1a1a",
        "inverse-primary": "#ffb2b9",
        "surface-container-highest": "#e4e2e2",
        "tertiary-fixed": "#ffd6fe",
        "surface": "#fbf9f8",
        "surface-bright": "#fbf9f8",
        "on-tertiary-fixed-variant": "#7b0090",
        "secondary": "#1a1a1a",
        "on-primary-container": "#fff9f9",
        "outline": "#916e71",
        "surface-dim": "#dbdad9",
        "secondary-fixed": "#d8e2ff",
        "on-primary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "primary-fixed-dim": "#ffb2b9",
        "on-secondary-container": "#fefcff",
        "error-container": "#ffdad6",
        "tertiary-fixed-dim": "#f9acff",
        "on-error-container": "#93000a",
        "surface-container": "#efeded",
        "on-primary-fixed-variant": "#91002f",
        "primary-fixed": "#ffdadc",
        "outline-variant": "#e6bcbf",
        "tertiary": "#ff4d00",
        "on-background": "#666666",
        "primary-container": "#e5004f",
        "on-secondary-fixed-variant": "#004493"
      },
      fontFamily: {
        "headline": ["Plus Jakarta Sans", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
    },
  },
  plugins: [],
}
